/**
 * components/LLMBrief.tsx
 * ────────────────────────
 * AI trade brief narrative display component.
 * Props:
 *   narrative — string | null | undefined  (from SEPAResult.narrative)
 *   quality   — SetupQuality
 */
"use client";

import * as React from "react";
import { Info } from "lucide-react";
import { cn } from "@/lib/utils";
import type { SetupQuality } from "@/lib/types";

// ── Quality → accent color ────────────────────────────────────────────────────

const qualityBorder: Record<SetupQuality, string> = {
  "A+":   "border-l-teal-500",
  "A":    "border-l-green-500",
  "B":    "border-l-amber-500",
  "C":    "border-l-orange-500",
  "FAIL": "border-l-red-500",
};

// ── Main component ───────────────────────────────────────────────────────────

interface LLMBriefProps {
  narrative: string | null | undefined;
  quality: SetupQuality;
}

export default function LLMBrief({ narrative, quality }: LLMBriefProps) {
  const accentBorder = qualityBorder[quality] ?? "border-l-zinc-600";

  // ── Empty state ─────────────────────────────────────────────────────────────
  if (!narrative) {
    return (
      <div className="rounded-xl border border-zinc-800/60 bg-zinc-900 p-6 flex items-start gap-3">
        <Info className="h-5 w-5 text-zinc-500 mt-0.5 shrink-0" />
        <p className="text-sm text-zinc-500 leading-relaxed">
          AI brief not available for this setup. Enable LLM in config to generate
          trade narratives.
        </p>
      </div>
    );
  }

  // ── Narrative card ──────────────────────────────────────────────────────────
  return (
    <div className="rounded-xl border border-zinc-800/60 bg-zinc-900 p-5 flex flex-col gap-3">
      {/* Heading */}
      <p className="text-[13px] font-semibold text-teal-400 uppercase tracking-widest">
        🤖 AI Trade Brief
      </p>

      {/* Blockquote */}
      <blockquote
        className={cn(
          "border-l-4 pl-4 py-1 rounded-r-md bg-zinc-800/40",
          accentBorder
        )}
      >
        <p className="text-sm text-zinc-300 italic leading-relaxed whitespace-pre-wrap">
          {narrative}
        </p>
      </blockquote>

      {/* Attribution */}
      <p className="text-[11px] text-zinc-500 font-mono">
        Generated by Groq · Llama 3.3 70B
      </p>

      {/* Disclaimer */}
      <div className="rounded-lg border border-zinc-800 bg-zinc-950/60 px-3 py-2.5">
        <p className="text-[11px] text-zinc-600 leading-relaxed">
          AI narrates rule outputs only. Not a buy/sell recommendation. All scoring
          is deterministic.
        </p>
      </div>
    </div>
  );
}
